export const FETCH_SUMMARY = "@summary/FETCH_SUMMARY";
export const SUMMARY_REQUEST = "@@summary/SUMMARY_REQUEST";
export const SUMMARY_SUCCESS = "@@summary/SUMMARY_SUCCESS";
export const SUMMARY_FAILURE = "@@summary/SUMMARY_FAILURE";
export const SELECT_TO_DISPLAY_REGION = "@@summary/SELECT_TO_DISPLAY_REGION";
export const SELECT_TO_DISPLAY_DISTRICT =
    "@@summary/SELECT_TO_DISPLAY_DISTRICT";
export const SELECT_TO_DISPLAY_COMMUNITY =
    "@@summary/SELECT_TO_DISPLAY_COMMUNITY";
export const SELECT_TO_DISPLAY_CITY = "@@summary/SELECT_TO_DISPLAY_CITY";
